# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0003_auto_20171031_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InfoTrack.Comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='InfoTrack.Post'),
        ),
    ]
