# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0009_auto_20171031_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='grade',
            new_name='PostType',
        ),
    ]
