# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0010_auto_20171031_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user.', primary_key=True, serialize=False),
        ),
    ]
