# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0011_auto_20171101_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
