# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0012_auto_20171101_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PostType',
            field=models.CharField(choices=[('---', '---'), ('clubinfo', 'ClubInfo'), ('courseinfo', 'CourseInfo'), ('lookforride', 'FreeRide'), ('tutor', 'TutorInfo'), ('rent', 'RentInfo')], default='---', max_length=50),
        ),
    ]
