# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0014_auto_20171125_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
