# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfoTrack', '0016_auto_20171126_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
